= Do we still need Conferences?
:jbake-date: 2021-05-08
:jbake-author: rdmueller
:jbake-type: post
:jbake-toc: true
:jbake-status: published
:jbake-tags: speaking
:jbake-lang: en
:doctype: article
:toc: macro

Since more than one year, all our conferences, meetups and user groups are now remote online events.
I attended lots of them - mostly as speaker - and I have to say, I don't like most of them.

So, let's analyze the current situation.

Als die Pandemie began und wir alle ins Home-Office gewechselt sind, haben wir auch unsere Präsenzveranstaltungen versucht 1:1 in die Online-Welt zu kopieren.
Schnell ist uns aufgefallen, dass diesen online Events etwas fehlte.
Der Hallway-Track ist ein ganz großer Nachteil.
Die Gespräche zwischen den Talks, beim Essen und bei den Abendveranstaltungen kann man nicht so einfach inn die Online-Welt bringen.
Um dem Gegenzusteuern sind Tools wie https://gather.town[Gather.Town], https://wonder.me[wonder.me], https://spatial.chat[spatial.chat] und https://workadventu.re/[workadventu.re] entstanden.
Sie versuchen das "herumlaufen und zufällig Menschen treffen" nachzubilden.
So ganz klappt das aber nicht für jeden.

Was ist bei schief gelaufen?

Als Architekt würde ich jetzt sagen, dass wir die Randbedingungen der alten Welt in die neue Welt mit hinein genommen haben.
Auch haben wir uns keine Gedanken um die neuen Randbedingungen gemacht.

Aber was sind die Randbedingungen der alten Welt?

== C01: Treffen an einem Ort

Wir wollen uns auf einer Konferenz austauschen.
Dies war früher nur möglich, wenn man sich an einem Ort getroffen hat.
Klingt heute verrückt, oder?

Das hat den netten Nebeneffekt, dass jeder aus seiner gewohnten Umgebung für ein paar Tage rausgerissen wird und sich voll auf die Konferenz konzentrieren kann.

== C02: Zeitlich begrenztes Event

Zeit ist Geld.
Das gilt umso mehr, wenn die Teilnehmer einer Konferenz anreisen und in einem Hotel übernachten müssen.
Je nach größe der Konferenz und Einzugsgebiet, haben sich 2-5 Tage als optimaler Zeitrahmen für eine Konferenz etabliert.
2-5 Tage können sich viele aus ihrem Projekt und dem Alltag ausklinken und 2-5 Tage rechtfertigen auch eine Anreise.

== C03: Möglichst viele Talks in kurzer Zeit

Wenn wir uns vor Ort treffen, vielleicht eine längere Anreise hatten und ein Hotel bezahlen, dann wollen wir auch etwas erleben.
Deshalb muss die Konferenz uns möglichst viele parallele Tracks bieten, damit für jeden etwas dabei ist.
Und zwischen den Tracks braucht es auch nicht viel zeitliche Pausen.
Snacks stehen über all vom Catering bereitgestellt zur Verfügung.
Wenn ich das Gespräch mit einem Speaker suche, dann opfere ich meine Snackpause und fange ihn an der Bühne ab.

== C04: Schlechtes Internet vor Ort

Auch nachdem die Konferenzveranstalter jahrelang Erfahrung mit dem Aufbau eines Konferenz-WLANs sammeln konnten und wir alle einen 4G-Hotspot zur Verfügung haben - so richtig möchte man sich nicht auf das Internet vor Ort verlassen und die Teilnehmer eines Workshops auffordern mal ein paar MB herunterzuladen oder vom Internet abhängiges Live-Coding in den Talk einzubauen, oder?

== C05: Abendveranstaltungen für die Angereisten

Zwischen den Veranstaltungstagen finden wir uns als Angereiste in einer Fremden Stadt einsam in einem Hotelzimmer wieder.
Diese Leere füllen die Veranstalter mit Abendveranstaltungen.
Und die haben es in sich.
Hier trifft man gleichgesinnte und kommt mit ihnen in's Gespräch.
Man tauscht sich aus, lernt ein paar Tricks und Kniffe und knüpft ein neues Netzwerk.

== C06: Das Veranstalten einer Konferenz kostet viel Geld

== C07: Speaker können froh sein, dass sie Speaker sein dürfen

== Speaker's Dinner

Nicht richtig am Arbeiten und nicht voll auf der Konferenz.

aufgezeichnete Talks => "playlist"

interaction with audience => Umfragen

Mehr möglichkeiten: greenscreen, live coding bei aufzeichnung

alt: schlechte Internetverbindung, Unterbringung im Hotel => Abendprogramm, Essen
neu: gute Internetverbindung, jeder vor seinem Rechner, Essen benötigt Zubereitungszeit, Abend gehört u.U. der Familie


Green Room for Speakers