:jbake-title: Using AI in Software Design
:jbake-type: page
:jbake-status: published

:diagram-server-url: https://kroki.io
:diagram-server-type: kroki_io

//== 🇩🇪 Phantastische Diagramme und wie Du sie selbst erstellst

//Die wichtigste Aufgabe eines Software-Architekten besteht darin, die Architektur zu kommunizieren.

//Neben den textuellen Inhalten gilt es auch, Grafiken zu erstellen. Getreu dem Motto "ein Bild sagt mehr als tausend Worte" helfen Diagramme bei einer effektiven und pragmatischen Dokumentation. Damit sie wirken, müssen sie leicht erfassbar, stets aktuell und korrekt sein..

//In diesem Talk spüren wir zuerst die Schwachstellen vieler Diagramme auf und überlegen uns anschließend, wie wir sie umgehen können. Das Ergebnis ist eine Checkliste für richtig gute, fast schon phantastische Architektur-Diagramme.

//Als Bonus werden wir aufzeigen, wie Diagramme wartbar mit dem Docs-as-Code Ansatz umgesetzt werden, um sie jederzeit aktuell und im Einklang mit der Architektur halten zu können.

== 🇬🇧 Using AI in Software Design: How ChatGPT Can Help With Creating a Solution Architecture

Artificial intelligence, or AI, is becoming a big part of our lives. One type of AI is Large Language Models (LLMs), like chatGPT. This talk will show how chatGPT can help with complex tasks in software design, such as the tasks in the iSAQB Advanced Exam.

We will delve into the intricacies of conversing with chatGPT, illustrating the strategies needed to generate productive prompts and effectively utilize the model as a sparring partner. The talk will exemplify these concepts by taking the audience on a step-by-step journey through the process of tackling the iSAQB Advanced Example Exam, utilizing chatGPT.

We will demonstrate how to prepare for a chat session with chatGPT, how to generate robust prompts, and how to manage the chat for optimal outcomes. We aim to highlight the model's capabilities as an interactive tool that can provide valuable insights and streamline the process of developing software architecture.

Whether you are a seasoned architect or a novice in the field, this presentation will equip you with novel techniques to navigate the challenging landscape of software architecture with the assistance of AI.

[cols="1,2h"]
|===
| Schwerpunkt	| Architektur
| Vortragstyp	| Best Practices
| Schwierigkeitsgrad	| Kein Schwierigkeitsgrad
| Keywords	| Architektur, chatGPT, iSAQB, AI
| Sprache	| English
| Features	| recorded demos
|===

=== Referenzen
