:jbake-title: Doku-Microsites mit jBake
:jbake-type: page
:jbake-status: published

== Doku-Microsites mit jBake

[cols="2"]
|===
a|
+++
<script async class="speakerdeck-embed" data-id="b535e91f527640aca7067e6c83ffc347" data-ratio="1.77777777777778" src="//speakerdeck.com/assets/embed.js"></script>
+++
a|
+++
<iframe width="560" height="315" src="https://www.youtube.com/embed/U8o9UuYlm9c?list=PLhB0zxn4tPQY8RunMJZepyJBPKYwFYVW-" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
+++
|===
Dokumentation in Markdown oder AsciiDoc zu erstellen ist einfach.
GitHub, GitLab und Bitbucket zeigen die Dokumente schon gleich im Repository als HTML-Seite an.
Doch wie bekomme ich aus diesen Dokumenten jetzt eine schicke Website hin, die nicht nur das Projekt dokumentiert, sondern auch das Projekt über eine nette Landingpage vorstellt, die Architektur bereitstellt und einen Newsfeed anbietet?

In diesem Vortrag zeige ich, warum sich jBake gerade für Java-Projekte ausgezeichnet eignet um für jedes Projekte mit wenig Aufwand eine schicke Microsite zu erstellen - vom Plain-Text-Dokument bis zur veröffentlichten Website mit TLS.

Dabei werde ich viele Tricks und Kniffe aus dem Projektalltag einfliessen lassen.
Landingpage, Architekturdokumentation mit arc42, Anwenderdoku mit AsciiDoc, Blog mit RSS-Feed und eine Suche werden kombiniert und einfach in das bestehende Projekt-Repository entsprechend dem Docs-as-Code-Ansatz integriert.
Über ein Open Source Template wird er Einstieg in die Erstellung einer eigenen Microsite nach dem Vortrag erleichtert.

siehe auch link:ArcDocs-with-Microsites.html[Architekturdokumentation mit Microsites]
