:jbake-title: Phantastische Diagramme
:jbake-type: page
:jbake-status: published

:diagram-server-url: https://kroki.io
:diagram-server-type: kroki_io

== 🇩🇪 Phantastische Diagramme und wie Du sie selbst erstellst

Die wichtigste Aufgabe eines Software-Architekten besteht darin, die Architektur zu kommunizieren.

Neben den textuellen Inhalten gilt es auch, Grafiken zu erstellen. Getreu dem Motto "ein Bild sagt mehr als tausend Worte" helfen Diagramme bei einer effektiven und pragmatischen Dokumentation. Damit sie wirken, müssen sie leicht erfassbar, stets aktuell und korrekt sein..

In diesem Talk spüren wir zuerst die Schwachstellen vieler Diagramme auf und überlegen uns anschließend, wie wir sie umgehen können. Das Ergebnis ist eine Checkliste für richtig gute, fast schon phantastische Architektur-Diagramme.

Als Bonus werden wir aufzeigen, wie Diagramme wartbar mit dem Docs-as-Code Ansatz umgesetzt werden, um sie jederzeit aktuell und im Einklang mit der Architektur halten zu können.

== 🇬🇧 Phantastic Diagrams and how to create them yourself

The most important task of a software architect is to communicate the architecture.

In addition to textual content, it is also important to create diagrams. True to the motto "a picture is worth a thousand words", diagrams help with effective and pragmatic documentation. In order for them to be effective, they must be easy to grasp, always up-to-date and correct...

In this talk, we first track down the weak points of many diagrams and then consider how to work around them. The result is a checklist for really good, almost fantastic architectural diagrams.

As a bonus, we will show how to implement diagrams in a maintainable way using the Docs-as-Code approach to keep them up-to-date and in line with the architecture at all times.


[cols="1,2h"]
|===
| Schwerpunkt	| Architektur
| Vortragstyp	| Best Practices
| Schwierigkeitsgrad	| Kein Schwierigkeitsgrad
| Keywords	| Architektur, Diagramme, Dokumentation, C4
| Sprache	| Deutsch
| Features	| Slot mit Demo
|===

=== Referenzen

* https://www.innoq.com/de/articles/2022/09/better-architecture-diagrams/[Gernot Starke: 1×1 guter Architekturdiagramme]
* https://leanpub.com/praxisbuchdocs-as-code/[Ralf D. Müller et.al.: Einführung in Docs-as-Code]
* https://c4model.com/assets/software-architecture-diagram-review-checklist.pdf[Simon Brown: Software Architecture Diagram Review Checklist]
* https://conferences.oreilly.com/software-architecture/sa-eu-2018/public/schedule/detail/68915.html[Jochem Schulenklopper: How to improve your architectural visualizations]

:kroki-server-url: kroki.io

[plantuml]
----
skinparam legendBackgroundColor transparent
skinparam legendBorderColor transparent
legend right
{{
    scale 0.8
    skinparam defaultFontSize 14
    skinparam defaultBackroundColor white
    !procedure $entry($type, $label, $scale=1)
        {{\nscale $scale \nskinparam backgroundcolor transparent\nlabel " " as A\nlabel " " as B\n $type \n}} => $label
    !endprocedure
    map "<b>Legende</b>" as legend #white {
        $entry("database db", "\nDatenbank", 0.7)
        $entry("A -> B #green", "Database Access")
    }
}}
endlegend
----
