:jbake-title: Portfolio as Code – Homepage für ITler
:jbake-type: page
:jbake-status: published

== Portfolio as Code – Homepage für ITler

Auch wenn wir als ITler derzeit auf dem Arbeitsmarkt umworben werden, muss man uns erst mal finden. Neben der Präsenz auf diversen beruflichen Kontaktbörsen bietet sich das Erstellen einer eigenen Internetseite an, auf der wir uns präsentieren können. Aber nicht jeder möchte sich mit Design und Layout auseinandersetzen. Zum Glück gibt es mittlerweile Werkzeuge, die auf uns Entwickler zugeschnitten sind und pragmatische, aber trotzdem ansehnliche Ergebnisse produzieren.

Getreu dem Motto "Everything as Code" unterstützen sie auch bei der Automatisierung des kompletten Entwicklungsprozesses bis zur Auslieferung und vor allem bei der kontinuierlichen Pflege der Webseite.

=== Vorkenntnisse

* Keine besonderen Vorkenntnisse nötig

++++
<script async class="speakerdeck-embed" data-id="992a80e0dbee45d4ae47549097348ff2" data-ratio="1.77777777777778" src="//speakerdeck.com/assets/embed.js"></script>
++++
