:jbake-title: Spock und Geb: Übersichtlich und nachvollziehbar Testen für alle!
:jbake-type: page
:jbake-status: published

== Spock und Geb: Übersichtlich und nachvollziehbar Testen für alle!

Bei automatisierten Tests ist es oftmals nicht einfach nachzuvollziehen was getestet wurde. Des Weiteren laufen Tests meist durch und geben nur im Fehlerfall etwas aus. Wie soll man mit dem Fachbereich kommunizieren, was getestet wurde?

Die beiden auf Groovy basierenden Frameworks Spock und Geb sorgen seit einiger Zeit für Aufsehen in der Java-Welt. Über Spock werden die Tests schon um einiges lesbarer. Durch die zusätzliche Nutzung von Geb lassen sich funktionale Tests aus der Sicht des Nutzers erstellen - so zu sagen die automatisierte Testfahrt der Applikation. Was noch fehlt sind gute Reports, die das Testvorgehen für alle Beteiligten nachvollziehbar machen.

++++
<div class="row">
    <div class=" col-xs-12 col-sm-6 col-md-6 col-lg-6 col-sm-offset-3 col-md-offset-3 col-lg-offset-3">
        <script async
            class="speakerdeck-embed"
            data-id="a5e3259364ba4c1dafc4a89890209bf2"
            data-ratio="1.41436464088398"
            src="//speakerdeck.com/assets/embed.js">
        </script>
    </div>
</div>
++++

= Spock & Geb: Clear and comprehensible tests!


++++
<div class="row">
    <div class=" col-xs-12 col-sm-6 col-md-6 col-lg-6 col-sm-offset-3 col-md-offset-3 col-lg-offset-3">
<script async class="speakerdeck-embed" data-id="2d2e6ba43fb54ab296e64ce52168aa75" data-ratio="1.77777777777778" src="//speakerdeck.com/assets/embed.js"></script>
</div>
</div>
++++
