= Stoizismus - Praktische Philosophie für den IT-Alltag
:jbake-date: 2022-08-30
:jbake-author: jdienst
:jbake-type: post
:jbake-toc: true
:jbake-status: published
:jbake-tags: stoicism, philosphy
:doctype: article
:toc: macro

_Dieser Post basiert auf meinem Vortrag *Stoizismus - Eine Praktische Philosophie für den IT-Alltag*. 
Das Video dazu ist auf link:https://fiveandahalfstars.ninja/talks/johannesdienst_talks.html[meiner Talkseite] demnächst verlinkt.

== Philosophie für IT?
Warum Philosophie auf einem Tech-Blog? Mag sich der Eine oder die andere Fragen. Für mich ist der Umgang mit Menschen manchmal schwierig, 
da ich eine eher kurze _Zündschnur_ besitze. Technik ist einfach und logisch im Vergleich zum Verhalten von so manchen Kolleg:innen.
Gerade in der heutigen Arbeitswelt lässt sich Kommunikation nicht mehr vermeiden. Also musste ich einen Weg für mich finden, professionell
mit Herausforderungen in diesem Bereich umzugehen.

Ich weiß nicht mehr wo es war, aber so um 2018 bin ich über den Stoizismus gestolpert und habe mich seitdem immer weiter damit beschäftigt.
Inzwischen bin ich der festen Überzeugung, dass diese Philosophie für jede:n ein Gewinn ist, der sich auch nur damit auseinandersetzt.
Deswegen erzähle ich jedem davon, der es nicht hören will ;-)

== Stoizismus - Praktische Philosophie

Philosophie hat in vielen Köpfen etwas mit weltfremden Diskussionen zu tun, die keinen praktischen Nutzen haben im Alltag.

Im Gegensatz dazu stehen die *Praktischen Philosophien*, zu denen auch der _Stoizismus_ gehört. In diesen Philosophien wird die Frage gestellt:

----
Wie lebe ich ein gutes Leben?
----

Ich empfehle den obigen Satz zweimal zu lesen, denn es wird explizit nicht von glücklich gesprochen. In der heutigen Zeit wird sehr oft dazu aufgerufen nach
dem glücklichen Leben zu streben. In der stoischen Philosophie geht es darum ein Leben in Einklang mit den stoischen Tugenden zu leben und der *perfekte* Stoiker
zu werden, der unter anderem sein Urteilsvermögen ungetrübt von Emotionen einsetzen kann. Da wir Menschen sind und Emotionen zu unserer Natur gehören ist dieses Ideal
natürlich nicht erreichbar. Dazu aber später mehr.

Gehen wir zum nächsten Abschnitt, in dem ich die Kernaussagen des Stoizismus zusammenfasse. Hier bitte nicht vergessen, dass ich noch ein Schüler des Stoizismus
bin und es sehr viele verschiedene Interpretierungsnuancen in der Literatur gibt!

== Kernideen

Eine wunderschöne graphische Zusammenfassung der stoizistischen Kernideen ist das stoische Glücksdreieck. Das höchste gut ist _Verantwortung zu übernehmen_ für sein
Tun und seine Reaktionen. Das ist aber erst in möglich, wenn die beiden Fundamente _Leben in Aretè_ und _Fokus auf das Kontrollierbare_ gemeistert wurden.
In der Mitte steht das höchste Ziel: Eudaimonia. Ein zusammengesetztes Wort mit der Bedeutung mit seinem inneren Selbst (_Daimon_) im Reinen zu sein (_Eu_).

link:blog/2022/stoicism_happiness_triangle_de.drawio.png[Stoisches Glückdreieck aus dem Buh "The Little Book of Stoicism" von Jonas Salzgeber]

=== Leben in Areté

In dieser Ecke geht es um Tugenden und darum nach diesen zu leben. Das beudetet in unserem Handeln gutes Urteilsvermögen zu zeigen, die zu diesen Tugenden passen.

* *Weißheit*: Im Sinne von guter Urteilsfähigkeit, die überlegt ist und nicht gedankenlos
* *Gerechtigkeit*: Hier geht es um die Beziehung zu unseren Mitmenschen, in denen integer und fair gehandelt werden soll
* *Mut*: Zu wissen, wie in einer Situation richtig zu handeln. Entgegen jedweden Widerstands
* *Selbst-Disziplin*: Im Stoizismus vor allem die angemessene Reaktion auf Emotionen und starkes Begehren in jeder Hinsicht

Noch hinzuzufügen ist, dass für Stoiker alle Tugenden wichtig sind. Wird eine nicht gelebt, dann wird es schwierig Eudaimonia zu erreichen. 
Trotzdem haben alle Stoiker in ihrem Leben festgestellt, dass sie Probleme haben immer nach den Tugenden zu leben.

Seneca ist ein sehr berühmtes Beispiel. Es einer der reichsten Männer seiner Zeit wurde ihm oft Heuchlerei vorgeworfen, da er im Überfluss lebte. Er pflegte 
ein abendliches Journal in dem er offen über die verschiedenen Situationen schrieb. Er war sich seinen Fehlern bewusst. Wichtig ist nur, sein Bestes zu geben!

=== Fokus auf das Kontrollierbare_

Umgangsprachlich wird der Begriff _stoisch_ mit Gefühlslosigkeit gleichgesetzt. Das kommt daher, dass Stoiker ihren Fokus auf das Kontrollierbare legen.
Dazu unterteilen sie Dinge die Passieren in vier Kategorien:

. *Kein Einfluss*: Fast alle externen Einflüsse
. *Teilweiser Einfluss*: Die Reaktion auf unser Verhalten oder auch Gesundheit
. *Indifferent aber bevorzugt*: Reich oder arm zu sein sollte keinen Einfluss darauf haben, ob wir ein gutes stoisches Leben führen. Reich sein ist aber definitiv angenehmer ;)
. *Hoher Einfluss*: Die Wichtigste Kategorie, aber auch die Kleinste. Unser Urteilsvermögen und Handeln

Nur die vierte Kategorie können wir wirklich kontrollieren. Das heißt, sich zum Beispiel über das Wetter zu beschweren ist nicht sinnvoll, 
da es nur akzeptiert werden kann. Die Kunst ist es, in jeder Situation in Einklang mit den stoischen Tugenden zu reagieren.

=== Verantwortung übernehmen

Ohne die beiden Fundamente kann keine Verantwortung übernommen werden. Was _wirklich_ in unserer Verantwortung liegt ist _wie_ wir auf ein Ereignis reagieren.
So ist es dem Wetter (um bei dme Beispiel zu bleiben) ziemlich egal, ob wir uns darüber freuen, indifferent oder genervt sind. Es liegt also in unserer 
Verantwortung zu entscheiden, wie wir uns fühlen.

Das ist einfach geschrieben, aber sehr schwierig umzusetzen! Deswegen sehen wir uns in den nächsten Abschnitten an, welchen praktischen Nutzen
uns das bringt und welche stoischen Übungen es gibt, mit denen wir das stoische Glücksdreieck verinnerlichen können.

== Praktischer Nutzen

Für mich der größte praktische Nutzen war die Erkenntnis, dass wir einen hohen Einfluss auf unsere Reaktionen auf externe Ereignisse haben.
Sehen wir uns insbesondere Social Media an, dann sehen wir genau das Gegenteil. Hier ist die *Empörungskultur* am Werk. Auf jeden Tweet wird sofort 
scharf in den Kommentaren reagiert bis hin zu Beleidigungen. Sehr oft unberechtigt und ohne Nachzudenken, dass das Medium sehr beschränkt ist.

TODO Bild mit Instant-Reaktion

Stattdessen können wir uns einen Effekt zu Nutze machen, der uns wieder die Kontrolle zurück gibt. Es gibt eine kurze Zeitspanne zwischen dem Ereignis und 
unserer spontanen Reaktion darauf. Mir persönlich ist er erst aufgefallen nachdem ich davon gewusst habe. Ich rate daher dazu sich selbst genauer zu beobachten.
Die Chancen stehen sehr gut, dass es bei allen Menschen so ist ;-). Greifen wir genau zu diesem Zeitpunkt ein können wir rational überlegen, was die passende 
Reaktion auf ein Ereignis ist. Dadurch gewinnen wir die Kontrolle zurück und lösen uns davon nur Emotionsgesteuert zu handeln. 

TODO Bild mit Pause + passende Reaktion überlegen + erst dann handeln

=== Stoische Übungen
Es geht darum sich mental vorzubereiten und sich mental zu trainieren, wie es für jeden Muskel notwendig ist.

Übungen wie sich klar machen, was am Tag schief gehen kann etc.

== Weiterführende Gedanken und Leseempfehlungen

Es gibt noch viel mehr zu entdecken im Stoizismus als das, was ich hier beschrieben habe. Jedes mal, wenn ich wieder ein Buch in die Hand nehme und es lese kommen
neue Einsichten dazu. Ich kann nur empfehlen mit dem einsteigerfreundlichen Buch _The Little Book of Stoicism_ von Jonas Salzgeber loszulegen, da es sehr
konzentriert alle wichtigen Kernaussagen des Stoizismus verständlich rüberbringt.

=== Leseempfehlungen

* The Little Book of Stoicism - Jonas Salzgeber
* The Practicing Stoic - Farnsworth
* How to Think Like a Roman Emperor - Donald Robertson
* link:https://www.njlifehacks.com/[Webseite von Nils und Jonas Salzgeber]

toc::[]